spring:
  datasource:
    url: jdbc:mysql://localhost:3307/db
    username: user
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379
  cache:
    cache-names:
    - Student
    redis:
      key-prefix: test
debug: true
