spring:
  datasource:
    url: jdbc:mysql://localhost:3306/caching?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456789
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379
  cache:
    cache-names:
    - Student
    redis:
      key-prefix: test
debug: true
